// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Abi = "Rust" | { "C": { unwind: boolean, } } | { "Cdecl": { unwind: boolean, } } | { "Stdcall": { unwind: boolean, } } | { "Fastcall": { unwind: boolean, } } | { "Aapcs": { unwind: boolean, } } | { "Win64": { unwind: boolean, } } | { "SysV64": { unwind: boolean, } } | { "System": { unwind: boolean, } } | { "Other": string };
