// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericBound } from "./GenericBound";
import type { Term } from "./Term";

/**
 * The way in which an associate type/constant is bound.
 */
export type AssocItemConstraintKind = { "equality": Term } | { "constraint": Array<GenericBound> };
