// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttributeRepr } from "./AttributeRepr";

/**
 * An attribute, e.g. `#[repr(C)]`
 *
 * This doesn't include:
 * - `#[doc = "Doc Comment"]` or `/// Doc comment`. These are in [`Item::docs`] instead.
 * - `#[deprecated]`. These are in [`Item::deprecation`] instead.
 */
export type Attribute = "non_exhaustive" | { "must_use": { reason: string | null, } } | { "export_name": string } | { "link_section": string } | "automatically_derived" | { "repr": AttributeRepr } | "no_mangle" | { "target_feature": { enable: Array<string>, } } | { "other": string };
