// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A constant.
 */
export type Constant = { 
/**
 * The stringified expression of this constant. Note that its mapping to the original
 * source code is unstable and it's not guaranteed that it'll match the source code.
 */
expr: string, 
/**
 * The value of the evaluated expression for this constant, which is only computed for numeric
 * types.
 */
value: string | null, 
/**
 * Whether this constant is a bool, numeric, string, or char literal.
 */
is_literal: boolean, };
