// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about the deprecation of an [`Item`].
 */
export type Deprecation = { 
/**
 * Usually a version number when this [`Item`] first became deprecated.
 */
since: string | null, 
/**
 * The reason for deprecation and/or what alternatives to use.
 */
note: string | null, };
