// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The value that distinguishes a variant in an [`Enum`] from other variants.
 */
export type Discriminant = { 
/**
 * The expression that produced the discriminant.
 *
 * Unlike `value`, this preserves the original formatting (eg suffixes,
 * hexadecimal, and underscores), making it unsuitable to be machine
 * interpreted.
 *
 * In some cases, when the value is too complex, this may be `"{ _ }"`.
 * When this occurs is unstable, and may change without notice.
 */
expr: string, 
/**
 * The numerical value of the discriminant. Stored as a string due to
 * JSON's poor support for large integers, and the fact that it would need
 * to store from [`i128::MIN`] to [`u128::MAX`].
 */
value: string, };
