// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolyTrait } from "./PolyTrait";

export type DynTrait = { 
/**
 * All the traits implemented. One of them is the vtable, and the rest must be auto traits.
 */
traits: Array<PolyTrait>, 
/**
 * The lifetime of the whole dyn object
 * ```text
 * dyn Debug + 'static
 *             ^^^^^^^
 *             |
 *             this part
 * ```
 */
lifetime: string | null, };
