// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Generics } from "./Generics";
import type { Id } from "./Id";

export type Enum = { generics: Generics, variants_stripped: boolean, variants: Array<Id>, impls: Array<Id>, };
