// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata of a crate, either the same crate on which `rustdoc` was invoked, or its dependency.
 */
export type ExternalCrate = { 
/**
 * The name of the crate.
 *
 * Note: This is the [*crate* name][crate-name], which may not be the same as the
 * [*package* name][package-name]. For example, for <https://crates.io/crates/regex-syntax>,
 * this field will be `regex_syntax` (which uses an `_`, not a `-`).
 *
 * [crate-name]: https://doc.rust-lang.org/stable/cargo/reference/cargo-targets.html#the-name-field
 * [package-name]: https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-name-field
 */
name: string, 
/**
 * The root URL at which the crate's documentation lives.
 */
html_root_url: string | null, };
