// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata of a crate, either the same crate on which `rustdoc` was invoked, or its dependency.
 */
export type ExternalCrate = { 
/**
 * The name of the crate.
 */
name: string, 
/**
 * The root URL at which the crate's documentation lives.
 */
html_root_url: string | null, };
