// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Type } from "./Type";

/**
 * The signature of a function.
 */
export type FnDecl = { 
/**
 * List of argument names and their type.
 *
 * Note that not all names will be valid identifiers, as some of
 * them may be patterns.
 */
inputs: Array<[string, Type]>, 
/**
 * The output type, if specified.
 */
output: Type | null, 
/**
 * Whether the function accepts an arbitrary amount of trailing arguments the C way.
 *
 * ```ignore (incomplete code)
 * fn printf(fmt: &str, ...);
 * ```
 */
c_variadic: boolean, };
