// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Type } from "./Type";

export type FnDecl = { 
/**
 * List of argument names and their type.
 *
 * Note that not all names will be valid identifiers, as some of
 * them may be patterns.
 */
inputs: Array<[string, Type]>, output: Type | null, c_variadic: boolean, };
