// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Abi } from "./Abi";

/**
 * A set of fundamental properties of a function.
 */
export type FunctionHeader = { 
/**
 * Is this function marked as `const`?
 */
is_const: boolean, 
/**
 * Is this function unsafe?
 */
is_unsafe: boolean, 
/**
 * Is this function async?
 */
is_async: boolean, 
/**
 * The ABI used by the function.
 */
abi: Abi, };
