// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FnDecl } from "./FnDecl";
import type { Generics } from "./Generics";
import type { Header } from "./Header";

/**
 * Represents a function (including methods and other associated functions)
 */
export type Function = { decl: FnDecl, generics: Generics, header: Header, has_body: boolean, };
