// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionHeader } from "./FunctionHeader";
import type { FunctionSignature } from "./FunctionSignature";
import type { Generics } from "./Generics";

/**
 * A function declaration (including methods and other associated functions).
 */
export type Function = { 
/**
 * Information about the function signature, or declaration.
 */
sig: FunctionSignature, 
/**
 * Information about the function’s type parameters and `where` clauses.
 */
generics: Generics, 
/**
 * Information about core properties of the function, e.g. whether it's `const`, its ABI, etc.
 */
header: FunctionHeader, 
/**
 * Whether the function has a body, i.e. an implementation.
 */
has_body: boolean, };
