// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FnDecl } from "./FnDecl";
import type { Generics } from "./Generics";
import type { Header } from "./Header";

/**
 * A function declaration (including methods and other associated functions).
 */
export type Function = { 
/**
 * Information about the function signature, or declaration.
 */
decl: FnDecl, 
/**
 * Information about the function’s type parameters and `where` clauses.
 */
generics: Generics, 
/**
 * Information about core properties of the function, e.g. whether it's `const`, its ABI, etc.
 */
header: Header, 
/**
 * Whether the function has a body, i.e. an implementation.
 */
has_body: boolean, };
