// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericParamDefKind } from "./GenericParamDefKind";

/**
 * One generic parameter accepted by an item.
 */
export type GenericParamDef = { 
/**
 * Name of the parameter.
 * ```rust
 * fn f<'resource, Resource>(x: &'resource Resource) {}
 * //    ^^^^^^^^  ^^^^^^^^
 * ```
 */
name: string, 
/**
 * The kind of the parameter and data specific to a particular parameter kind, e.g. type
 * bounds.
 */
kind: GenericParamDefKind, };
