// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Constant } from "./Constant";
import type { Type } from "./Type";

/**
 * One argument in a list of generic arguments to a path segment.
 *
 * Part of [`GenericArgs`].
 */
export type GenericArg = { "lifetime": string } | { "type": Type } | { "const": Constant } | "infer";
