// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericParamDef } from "./GenericParamDef";
import type { WherePredicate } from "./WherePredicate";

export type Generics = { params: Array<GenericParamDef>, where_predicates: Array<WherePredicate>, };
