// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericParamDefKind } from "./GenericParamDefKind";

export type GenericParamDef = { name: string, kind: GenericParamDefKind, };
