// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericParamDef } from "./GenericParamDef";
import type { Path } from "./Path";
import type { PreciseCapturingArg } from "./PreciseCapturingArg";
import type { TraitBoundModifier } from "./TraitBoundModifier";

/**
 * Either a trait bound or a lifetime bound.
 */
export type GenericBound = { "trait_bound": { 
/**
 * The full path to the trait.
 */
trait: Path, 
/**
 * Used for Higher-Rank Trait Bounds (HRTBs)
 * ```text
 * where F: for<'a, 'b> Fn(&'a u8, &'b u8)
 *          ^^^^^^^^^^^
 *          |
 *          this part
 * ```
 */
generic_params: Array<GenericParamDef>, 
/**
 * The context for which a trait is supposed to be used, e.g. `const
 */
modifier: TraitBoundModifier, } } | { "outlives": string } | { "use": Array<PreciseCapturingArg> };
