// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericParamDef } from "./GenericParamDef";
import type { Path } from "./Path";
import type { TraitBoundModifier } from "./TraitBoundModifier";

export type GenericBound = { "trait_bound": { trait: Path, 
/**
 * Used for Higher-Rank Trait Bounds (HRTBs)
 * ```text
 * where F: for<'a, 'b> Fn(&'a u8, &'b u8)
 *          ^^^^^^^^^^^
 *          |
 *          this part
 * ```
 */
generic_params: Array<GenericParamDef>, modifier: TraitBoundModifier, } } | { "outlives": string } | { "use": Array<string> };
