// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericArg } from "./GenericArg";
import type { Type } from "./Type";
import type { TypeBinding } from "./TypeBinding";

export type GenericArgs = { "angle_bracketed": { args: Array<GenericArg>, bindings: Array<TypeBinding>, } } | { "parenthesized": { inputs: Array<Type>, output: Type | null, } };
