// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Abi } from "./Abi";

export type Header = { const: boolean, unsafe: boolean, async: boolean, abi: Abi, };
