// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opaque identifier for an item.
 *
 * It can be used to lookup in [`Crate::index`] or [`Crate::paths`] to resolve it
 * to an [`Item`].
 *
 * Id's are only valid within a single JSON blob. They cannot be used to
 * resolve references between the JSON output's for different crates.
 *
 * Rustdoc makes no guarantees about the inner value of Id's. Applications
 * should treat them as opaque keys to lookup items, and avoid attempting
 * to parse them, or otherwise depend on any implementation details.
 */
export type Id = string;
