// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Generics } from "./Generics";
import type { Id } from "./Id";
import type { Path } from "./Path";
import type { Type } from "./Type";

export type Impl = { is_unsafe: boolean, generics: Generics, provided_trait_methods: Array<string>, trait: Path | null, for: Type, items: Array<Id>, negative: boolean, synthetic: boolean, blanket_impl: Type | null, };
