// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

export type Import = { 
/**
 * The full path being imported.
 */
source: string, 
/**
 * May be different from the last segment of `source` when renaming imports:
 * `use source as name;`
 */
name: string, 
/**
 * The ID of the item being imported. Will be `None` in case of re-exports of primitives:
 * ```rust
 * pub use i32 as my_i32;
 * ```
 */
id: Id | null, 
/**
 * Whether this import uses a glob: `use source::*;`
 */
glob: boolean, };
