// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Constant } from "./Constant";
import type { Enum } from "./Enum";
import type { Function } from "./Function";
import type { GenericBound } from "./GenericBound";
import type { Generics } from "./Generics";
import type { Impl } from "./Impl";
import type { Import } from "./Import";
import type { Module } from "./Module";
import type { OpaqueTy } from "./OpaqueTy";
import type { Primitive } from "./Primitive";
import type { ProcMacro } from "./ProcMacro";
import type { Static } from "./Static";
import type { Struct } from "./Struct";
import type { Trait } from "./Trait";
import type { TraitAlias } from "./TraitAlias";
import type { Type } from "./Type";
import type { TypeAlias } from "./TypeAlias";
import type { Union } from "./Union";
import type { Variant } from "./Variant";

export type ItemEnum = { "module": Module } | { "extern_crate": { name: string, rename: string | null, } } | { "import": Import } | { "union": Union } | { "struct": Struct } | { "struct_field": Type } | { "enum": Enum } | { "variant": Variant } | { "function": Function } | { "trait": Trait } | { "trait_alias": TraitAlias } | { "impl": Impl } | { "type_alias": TypeAlias } | { "opaque_ty": OpaqueTy } | { "constant": { type: Type, const: Constant, } } | { "static": Static } | "foreign_type" | { "macro": string } | { "proc_macro": ProcMacro } | { "primitive": Primitive } | { "assoc_const": { type: Type, 
/**
 * e.g. `const X: usize = 5;`
 */
default: string | null, } } | { "assoc_type": { generics: Generics, bounds: Array<GenericBound>, 
/**
 * e.g. `type X = usize;`
 */
default: Type | null, } };
