// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fundamental kind of an item. Unlike [`ItemEnum`], this does not carry any additional info.
 *
 * Part of [`ItemSummary`].
 */
export type ItemKind = "module" | "extern_crate" | "use" | "struct" | "struct_field" | "union" | "enum" | "variant" | "function" | "type_alias" | "constant" | "trait" | "trait_alias" | "impl" | "static" | "extern_type" | "macro" | "proc_attribute" | "proc_derive" | "assoc_const" | "assoc_type" | "primitive" | "keyword";
