// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemKind = "module" | "extern_crate" | "import" | "struct" | "struct_field" | "union" | "enum" | "variant" | "function" | "type_alias" | "opaque_ty" | "constant" | "trait" | "trait_alias" | "impl" | "static" | "foreign_type" | "macro" | "proc_attribute" | "proc_derive" | "assoc_const" | "assoc_type" | "primitive" | "keyword";
