// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The way a [`ProcMacro`] is declared to be used.
 */
export type MacroKind = "bang" | "attr" | "derive";
