// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

export type Module = { is_crate: boolean, items: Array<Id>, 
/**
 * If `true`, this module is not part of the public API, but it contains
 * items that are re-exported as public API.
 */
is_stripped: boolean, };
