// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * A module declaration, e.g. `mod foo;` or `mod foo {}`.
 */
export type Module = { 
/**
 * Whether this is the root item of a crate.
 *
 * This item doesn't correspond to any construction in the source code and is generated by the
 * compiler.
 */
is_crate: boolean, 
/**
 * [`Item`]s declared inside this module.
 */
items: Array<Id>, 
/**
 * If `true`, this module is not part of the public API, but it contains
 * items that are re-exported as public API.
 */
is_stripped: boolean, };
