// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericParamDef } from "./GenericParamDef";
import type { Path } from "./Path";

/**
 * A trait and potential HRTBs
 */
export type PolyTrait = { 
/**
 * The path to the trait.
 */
trait: Path, 
/**
 * Used for Higher-Rank Trait Bounds (HRTBs)
 * ```text
 * dyn for<'a> Fn() -> &'a i32"
 *     ^^^^^^^
 * ```
 */
generic_params: Array<GenericParamDef>, };
