// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * A primitive type declaration. Declarations of this kind can only come from the core library.
 */
export type Primitive = { 
/**
 * The name of the type.
 */
name: string, 
/**
 * The implementations, inherent and of traits, on the primitive type.
 */
impls: Array<Id>, };
