// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacroKind } from "./MacroKind";

export type ProcMacro = { kind: MacroKind, helpers: Array<string>, };
