// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of `#[repr]`.
 *
 * See [AttributeRepr::kind]`.
 */
export type ReprKind = "rust" | "c" | "transparent" | "simd";
