// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A range of source code.
 */
export type Span = { 
/**
 * The path to the source file for this span relative to the path `rustdoc` was invoked with.
 */
filename: string, 
/**
 * One indexed Line and Column of the first character of the `Span`.
 */
begin: [number, number], 
/**
 * One indexed Line and Column of the last character of the `Span`.
 */
end: [number, number], };
