// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Generics } from "./Generics";
import type { Id } from "./Id";
import type { StructKind } from "./StructKind";

export type Struct = { kind: StructKind, generics: Generics, impls: Array<Id>, };
