// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetFeature } from "./TargetFeature";

/**
 * Information about a target
 */
export type Target = { 
/**
 * The target triple for which this documentation was generated
 */
triple: string, 
/**
 * A list of features valid for use in `#[target_feature]` attributes
 * for the target where this rustdoc JSON was generated.
 */
target_features: Array<TargetFeature>, };
