// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Constant } from "./Constant";
import type { Type } from "./Type";

export type Term = { "type": Type } | { "constant": Constant };
