// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Constant } from "./Constant";
import type { Type } from "./Type";

/**
 * Either a type or a constant, usually stored as the right-hand side of an equation in places like
 * [`AssocItemConstraint`]
 */
export type Term = { "type": Type } | { "constant": Constant };
