// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericBound } from "./GenericBound";
import type { Generics } from "./Generics";

export type TraitAlias = { generics: Generics, params: Array<GenericBound>, };
