// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A set of modifiers applied to a trait.
 */
export type TraitBoundModifier = "none" | "maybe" | "maybe_const";
