// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericBound } from "./GenericBound";
import type { Generics } from "./Generics";
import type { Id } from "./Id";

export type Trait = { is_auto: boolean, is_unsafe: boolean, is_object_safe: boolean, items: Array<Id>, generics: Generics, bounds: Array<GenericBound>, implementations: Array<Id>, };
