// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Generics } from "./Generics";
import type { Type } from "./Type";

/**
 * A type alias declaration, e.g. `type Pig = std::borrow::Cow<'static, str>;`
 */
export type TypeAlias = { 
/**
 * The type referred to by this alias.
 */
type: Type, 
/**
 * Information about the type parameters and `where` clauses of the alias.
 */
generics: Generics, };
