// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericArgs } from "./GenericArgs";
import type { TypeBindingKind } from "./TypeBindingKind";

export type TypeBinding = { name: string, args: GenericArgs, binding: TypeBindingKind, };
