// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericArgs } from "./GenericArgs";
import type { TypeBindingKind } from "./TypeBindingKind";

/**
 * Describes a bound applied to an associated type/constant.
 *
 * Example:
 * ```text
 * IntoIterator<Item = u32, IntoIter: Clone>
 *              ^^^^^^^^^^  ^^^^^^^^^^^^^^^
 * ```
 */
export type TypeBinding = { 
/**
 * The name of the associated type/constant.
 */
name: string, 
/**
 * Arguments provided to the associated type/constant.
 */
args: GenericArgs, 
/**
 * The kind of bound applied to the associated type/constant.
 */
binding: TypeBindingKind, };
