// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Generics } from "./Generics";
import type { Type } from "./Type";

export type TypeAlias = { type: Type, generics: Generics, };
