// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenericBound } from "./GenericBound";
import type { Term } from "./Term";

export type TypeBindingKind = { "equality": Term } | { "constraint": Array<GenericBound> };
