// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Generics } from "./Generics";
import type { Id } from "./Id";

export type Union = { generics: Generics, fields_stripped: boolean, fields: Array<Id>, impls: Array<Id>, };
