// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

export type VariantKind = "plain" | { "tuple": Array<Id | null> } | { "struct": { fields: Array<Id>, fields_stripped: boolean, } };
