// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Discriminant } from "./Discriminant";
import type { VariantKind } from "./VariantKind";

export type Variant = { 
/**
 * Whether the variant is plain, a tuple-like, or struct-like. Contains the fields.
 */
kind: VariantKind, 
/**
 * The discriminant, if explicitly specified.
 */
discriminant: Discriminant | null, };
