// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";

/**
 * Visibility of an [`Item`].
 */
export type Visibility = "public" | "default" | "crate" | { "restricted": { 
/**
 * ID of the module to which this visibility restricts items.
 */
parent: Id, 
/**
 * The path with which [`parent`] was referenced
 * (like `super::super` or `crate::foo::bar`).
 *
 * [`parent`]: Visibility::Restricted::parent
 */
path: string, } };
